language: java

cache:
  directories:
  # Cache maven's folder
  - "$HOME/.m2/repository"
  - "$HOME/.m2/wrapper"
  # Cache SonarQube's folder
  - "$HOME/.sonar/cache"

env:
  global:
  # Standard container name (schema: project/application). Used to build the image and push it to the repo
  - CONTAINER_NAME='enterpriseflowsrepository/api-infrastructure-quarkus'
  # Short container tag. Contains major, monor & patch values
  # Example: 1.7.2
  - CONTAINER_TAG_SHORT=$(./mvnw -q -Dexec.executable=echo -Dexec.args='${project.version}' --non-recursive exec:exec)
  # Long container tag. Used to select an unique build version. Allow to quickly know the build date plus the referenced git commit
  # Example: 1.7.2-20191113211021-921103d
  - CONTAINER_TAG_FULL="$CONTAINER_TAG_SHORT-$(date +'%Y%m%d%H%M%S')-$(git rev-parse --short HEAD)"
  # CONTAINER_REPO_HUB_DOCKER_COM_USERNAME
  - secure: qgDmSEbyl2TvFZBqRfPE2Ds2LC0wfzf9qpXKLtiY6U6hv/picbSFv5FQQo3zdom4cqC62a/dE7YRvZEvryjdxHm1kUFKn0qX8pBz0EHr0w0VRDt0Kh9CstKSevVMhdd6CP/w2G9d0ZLQtcMIn+7yjF6zxkV46BTRY65z9wEXLlrlK4nY0PO0DW9FTnvWeLbLWFcE5zvoUnOckna0yzdghqAGfrsuSC/Cbo8hlLRnUpFZgV7HMo4uDdDzj0VibhY3cgq60Jzy8Qy+7azrXvyMp/WioL9xp/I6ymngn8l829L2j0H8UiXdOK4wQ/BX49gbJFiBJuUq4xNezATVieI4XwP0mI1BukCJpXnaeAKUJFJwrWKZfxwItCGAh+zdybLKQVPqbFdM4siBNxjlw75zj5fMhXWJhOqhBpUG7lrftreLFtqH7C0zMHEcEp8P9PpgVhZIkaJzocJum6b1gbccKxjLsBP6jfokhQw8mzObgn3+rkC714e8g+U6wmu97SDSbxEqbIN4Fm+bR15vNkUQ1pxbweCdZee4TtllOr8uyVRaz2sjhAHzK5lkDhHX822Z19olMTBxh0cGzQXhqwFUWX3xppHRTwa9GnpK+vyT4Df8H5ikkPatQymziM0njq82obku05s8/CC/JS2GJfX0Obc1581zZ1JlTocj2XVJYsQ=
  # CONTAINER_REPO_HUB_DOCKER_COM_PASSWORD
  - secure: jEyaD0uoci1roM7Jl5/jNY2xXQiZd3aEy6RSNYEHoTqknCSRiNZbHKuprF8pz20KXggl8gXhRN1RK7hFzMK72OMtcgEBsAX0HVzEKzhCKtFtDg5A5/di5yWBuP/yclziG93HPWroHuo+Ri3twenEiGxflTE35XunLO1Dingl/8X9db+aCRM3zgtdUw7aWFCT2Zz/vis+O8+8r21BlF3mnAMhMQSqSb4jWZP2S4yzKRYZuHl2SBk0y47VMwL0OaSZzsJjMZVYi5d1hz1aH05/LEy/1kNfPj7Yf6AF4anDOuz8fQxX0kCtQXePFb3+biywivRMF0nsuW0+BEfC2bxJAa9xfS70je3V7yEBVsnXdaarn6PhpQRBeiKU8PxAldx35BQm/AgDAiB+fSOxjsSE0/Yh1MnSlS2+7sqqPdf50bhK/I7xDQyCqaYAEuB7wVKEZ1s0t172rPhPd0463Iy1TH6OYdIjj1Z8rZQe37YpX099aBCZfiNiik8yqnNfHOVK9CzVaGgT+uOS0g2RaFmEmMiN6J+lY+TcAbdtjYTaKDNAWlXzZ3nrrKxzJGJcVQTXew1T2xmhxKWBfVRD7mRYWFgFqRohB3b69t9fp+2wIPXjIZh2XjSL02fyC0Pr9CSl50XDCM63uqNxxsCwYVGZ+gw+0qBGXts5yNp046AMIzs=

services:
# We will create containers here!
- docker

addons:
  # Post build tests, quality and CVE detection by SonarQube
  sonarcloud:
    organization: enterpriseflowsrepository
    token:
      secure: ZJgfHHioYNUep/VFFL14ohzThIXvuFl1GzwkbS2dReRQMJjGj4V6dW9IMkDE58P2E8bMIohVDxTXLG9t7H7t/+iCZkPJThATzxCd+Fc/Z0lUhypROz16TaJ3M6mikBPkCsXVtuGXdIrbS0XS1XtfSzuDEM0w/OPQKpIFtmfoTBC8pjUmmy7wKlfxPdsZQYKw5sQGOWVkafrb19i2XcIOxR+AjRmnuqsdf3xofr+qQO5KOIzwv4QnUfWv2kqZ/o8+ICF6SXtUfU/gx6vBGzJCRiYgyTCJ9KhOPJkkGVswoy2XjipTHNySuXXkQGYvrVpn4TZj4Foc3n2LJCrIdnmfObZFyNHm5b0WGo6gXrLOCzQI0yY++FLulXrloi+Xf7gceHkRHeAMaRWPTEtIp5NOtppI5J4+rox7xdLXk9gmzEyvxVj6pGSfxALGXzIYtOFx1xflZgFTk3ptcdKq2DgZ07/GmMZD7ciOxkvOyJhvbIsPLf9RSsfJ0FutezDSen53/2quJioBwo0CG3hjxspejGC30OM9uqGuwdQtbf/ApdKiUr24yJ1/fdZ2eu7aElaciWOK8kNh6lfaqDamUcuGHUK5zMYvntPRaADyFGvJcuywQ8U2aRo2vY7zVlOdsfLt91V+HIJhaGXCerpjg9RT99psfpUEywwoMLcCbqqKfH8=
  apt:
    packages:
    # Force usage of the latest Docker version
    # See: https://docs.travis-ci.com/user/docker/#installing-a-newer-docker-version
    - docker-ce

jdk:
- openjdk11

before_install:
# Fix maven memory consumption within Travis
- echo "MAVEN_OPTS='-Xmx2048M -Xss128M -XX:+CMSClassUnloadingEnabled -XX:+UseG1GC -XX:-UseGCOverheadLimit'" > $HOME/.mavenrc
# Define maven custom repo (requirement for 'api-module-quarkus')
- cp .travis.settings.xml $HOME/.m2/settings.xml

script:
# Install the maven dependencies
- ./mvnw clean install
# Test the pre-build
- ./mvnw clean verify
# Build the container (binaries are built into a multistage container)
- docker build --file src/main/docker/Dockerfile -t "$CONTAINER_NAME" .
# Test the container by attacking the app
- ./src/main/docker/security-owasp-zap.sh

after_success:
# Run SonarQube
- ./mvnw clean org.jacoco:jacoco-maven-plugin:prepare-agent install sonar:sonar -Dsonar.projectKey=EnterpriseFlowsRepository_api-infrastructure-quarkus

notifications:
  # Notify each build on Slack
  slack: enterpriseflowsrepo:I2PkD1iUs0lMR3Zon4ciy5zS

deploy:
# Push builds with default tags to 'docker.io'
- provider: script
  script: bash ./src/main/docker/container-push.sh -r docker.io -u "$CONTAINER_REPO_HUB_DOCKER_COM_USERNAME" -p "$CONTAINER_REPO_HUB_DOCKER_COM_PASSWORD" -i "$CONTAINER_NAME" -v "$CONTAINER_TAG_SHORT" -w "$CONTAINER_TAG_FULL" -a default
  on:
    all_branches: true
# Push builds with stable tags to 'docker.io'
- provider: script
  script: bash ./src/main/docker/container-push.sh -r docker.io -u "$CONTAINER_REPO_HUB_DOCKER_COM_USERNAME" -p "$CONTAINER_REPO_HUB_DOCKER_COM_PASSWORD" -i "$CONTAINER_NAME" -v "$CONTAINER_TAG_SHORT" -w "$CONTAINER_TAG_FULL" -a stable
  on:
    branch: master
