steps:

  # Infra: Update the Google Cloud Run service
  - name: 'gcr.io/cloud-builders/gcloud'
    args: [
      'beta', 'run',
      'deploy', 'api-infrastructure-quarkus',
      '--image', 'enterpriseflowsrepository/api-infrastructure-quarkus:latest', 
      '--region', '$_REGION',
      '--platform', 'managed',
      '--allow-unauthenticated']

timeout: 660s
tags: ['api-infrastructure-quarkus']
