steps:
  # Clone Git local
#  - name: gcr.io/cloud-builders/git
#    args: ["fetch", "--unshallow"]

  # Maven compile
  - name: 'gcr.io/cloud-builders/mvn'
    args: ['install']

  # Create image Docker
  - name: "gcr.io/cloud-builders/docker"
#    args: ["build", "-t", "eu.gcr.io/$PROJECT_ID/api-properties-quarkus", "--file", "Dockerfile.native", "."]
    args: ["build", 
            "-f", "src/main/docker/Dockerfile.jvm", 
            "-t", "enterprise-flows-repository/api-properties-quarkus:jvm", 
            "."]
    dir: src/main/docker

  # Tag image for Repository
  - name: "gcr.io/cloud-builders/docker"
    args: ["tag", "enterprise-flows-repository/api-properties-quarkus:native", "eu.gcr.io/$PROJECT_ID/api-properties-quarkus:jvm"]

  # Push into Docker Repository
  - name: "gcr.io/cloud-builders/docker"
    args: ["push", "eu.gcr.io/$PROJECT_ID/api-properties-quarkus:jvm"]

  # Deploy K8S configuration
  - name: "gcr.io/cloud-builders/kubectl"
    args:
      - apply
      - -f
      - src/main/k8s/
      - --record
    env:
      - "CLOUDSDK_COMPUTE_REGION=$_REGION"
      - "CLOUDSDK_CONTAINER_CLUSTER=$_CLUSTER_NAME"

timeout: 660s
tags: ['api-properties-quarkus']
images: ["eu.gcr.io/$PROJECT_ID/api-properties-quarkus"]
