apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  name: api-infrastructure-quarkus
  labels:
    app: api-infrastructure-quarkus
spec:
  selector:
    matchLabels:
      app: api-infrastructure-quarkus
  replicas: 1 
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: api-infrastructure-quarkus
    spec:
      containers:
      - name: api-infrastructure-quarkus
        image: enterprise-flows-repository/api-infrastructure-quarkus:jvm
        ports:
        - containerPort: 8081
        # resources:
        #   requests:
        #     cpu: 200m
        #     memory: 100Mi
        #   limits:
        #     cpu: 400m
        #     memory: 200Mi
        #livenessProbe:
        #  httpGet:
        #    path: /
        #    port: 8080
        #  initialDelaySeconds: 20
        #  timeoutSeconds: 10
        #  periodSeconds: 15
