apiVersion: v1
kind: Service
metadata:
  name: api-infrastructure-quarkus
  namespace: default
  labels:
    app: api-infrastructure-quarkus
spec:
  type: LoadBalancer
  selector:
    app: api-infrastructure-quarkus
  ports:
  - name: http
    port: 8080
    targetPort: 8080
